baseURL = "https://leanstudy.github.io/blog/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "en"
# 网站语言, 仅在这里 CN 大写
languageCode = "en-US"
# 是否包括中日韩文字
hasCJKLanguage = true
# 网站标题
title = "學無止境"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "hyde"

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
